export const ADD_ELEMENT = 'ADD_ELEMENT';
export const ADD_COURSE = 'ADD_COURSE';
export const ADD_LESSON = 'ADD_LESSON';
export const REMOVE_ELEMENT = 'REMOVE_ELEMENT';
export const REMOVE_LESSON = 'REMOVE_LESSON';
export const REMOVE_COURSE = 'REMOVE_COURSE';
export const SHIFT_ELEMENT = 'SHIFT_ELEMENT';
export const UPDATE_ELEMENT = 'UPDATE_ELEMENT';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const GET_ALL_LESSONS = 'GET_ALL_LESSONS';

